# Generated by Django 3.0.6 on 2020-06-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='Null', upload_to='pics')),
                ('desc', models.TextField()),
                ('companyname', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='Null', upload_to='pics')),
                ('f_name', models.CharField(max_length=70)),
                ('l_name', models.CharField(max_length=70)),
                ('postn', models.CharField(max_length=100)),
                ('twitter', models.CharField(default='twitter.com', max_length=150)),
                ('facebook', models.CharField(default='facebook.com', max_length=150)),
                ('git', models.CharField(default='github.com', max_length=150)),
                ('link', models.CharField(default='linkedin.com', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('datentime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
