# Generated by Django 3.0.6 on 2020-06-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_addesc_dsdesc_mldesc_wddesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='addesc',
            name='state',
            field=models.CharField(default='Null', max_length=10),
        ),
        migrations.AddField(
            model_name='dsdesc',
            name='state',
            field=models.CharField(default='Null', max_length=10),
        ),
        migrations.AddField(
            model_name='mldesc',
            name='state',
            field=models.CharField(default='Null', max_length=10),
        ),
        migrations.AddField(
            model_name='wddesc',
            name='state',
            field=models.CharField(default='Null', max_length=10),
        ),
    ]
