# Generated by Django 3.0.6 on 2020-07-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200703_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='addesc',
            name='img_alt',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='img_alt',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dsdesc',
            name='img_alt',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mldesc',
            name='img_alt',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wddesc',
            name='img_alt',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
