# Generated by Django 3.0.6 on 2020-07-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200703_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='anddev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('meta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('meta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='digseo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('meta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='maclea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('meta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='webdev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('meta', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='img_alt',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='summary',
        ),
        migrations.AddField(
            model_name='blog',
            name='meta',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
