# Generated by Django 3.0.6 on 2020-07-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200703_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('meta', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='ZAPPAD', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='heading',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='img_alt',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='imgs',
            field=models.ImageField(default='Null', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
